# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master, actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./gradlew testMockedDebugUnitTest assembleDebug

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./app/build/test-results/testMockedDebugUnitTest/*.xml
        
      - name: Upload apks
        uses: actions/upload-artifact@v2
        with:
          name: home2.apk
          path: ./app/build/outputs/apk/**/*.apk
